# -*- coding: utf-8 -*-
"""Tratando_dados_dicionario.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lAayNoVnzCttKIKCT3KH2v95QQEXn4Cl
"""

# Carregando os pacotes
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', None)

# dicionário dos dados
df = pd.read_excel('/content/dicionario_PNS_microdados_2019.xls', skiprows=1)

df.head()

# Pegando as colunas de interesse
colunas = ['Código\nda\nvariável','Unnamed: 4','Categorias','Unnamed: 6']

df = df[colunas]

# Remova as linhas com NA na coluna "tipo"
df = df.dropna(subset=['Categorias'])

# Removendo a primeira linha
df = df.drop(df.index[0])

# Renomeando as colunas
df = df.rename(columns={
    'Código\nda\nvariável': 'Codigo da variavel',
    'Unnamed: 4': 'Descricao_variavel',
    'Categorias': 'Tipo',
    'Unnamed: 6': 'Descricao_tipo'
})

df['Codigo da variavel'] = df['Codigo da variavel'].fillna(method='ffill')
df['Descricao_variavel'] = df['Descricao_variavel'].fillna(method='ffill')

df.head(5)

# Dicionário de mapeamento de unidades federativas para regiões
mapa_regioes = {
    
    # Rondonia
    '11': 'Norte',
    # Acre
    '12': 'Norte',
    #Amazonas
    '13': 'Norte',
    # Roraima
    '14': 'Norte',
    # Pará
    '15': 'Norte',
    # Amapá
    '16': 'Norte',
    #Tocantis
    '17': 'Norte',
    # Maranhao
    '21': 'Nordeste',
    # Piaui
    '22': 'Nordeste',
    #Ceará
    '23': 'Nordeste',
    # Rio Grande do Norte 
    '24': 'Nordeste',
    # Paraiba
    '25': 'Nordeste',
    # Pernambuco
    '26': 'Nordeste',
    # Alagoas
    '27': 'Nordeste',
    # Sergie
    '28': 'Nordeste',
    #Bahia
    '29': 'Nordeste',
    # Minas Gerais
    '31': 'Sudeste',
    # Espirito Santo
    '32': 'Sudeste',
    # Rio de Janero
    '33': 'Sudeste',
    # Sao Paulo
    '35': 'Sudeste',
    # Paraná
    '41': 'Sul',
    # Santa Catarina
    '42': 'Sul',
    # Rio Grande do Sul
    '43': 'Sul',
    # Mato Grosso do Sul
    '50': 'Centro-Oeste',
    # Mato Grosso
    '51': 'Centro-Oeste',
    # Goias
    '52': 'Centro-Oeste',
    # Distrito Federal
    '53': 'Centro-Oeste'
}

# Unidade da federação - V0001
# Tipo de situação censitária: Urbano, rural - V0026
# Sexo - C006
# Idade do morador na data de referência - C008
# Cor ou raça - C009
# Sabe ler e escrever - D001
# Qual foi o curso mais elevado que ___frequentou  - D00901 
# Quando o(a) Sr(a) sobe uma ladeira, um lance de escadas ou caminha rápido no plano, sente dor ou desconforto no peito - N004
# Quando o(a) Sr(a) caminha em lugar plano, em velocidade normal, sente dor ou desconforto no peito - N005
# Nas duas últimas semanas, com que frequência o(a) Sr(a) teve problemas no sono, como dificuldade para adormecer, acordar frequentemente à noite ou dormir mais do que de costume? - N010
# Nas duas últimas semanas, com que frequência o(a) Sr(a) teve problemas por não se sentir descansado(a) e disposto(a) durante o dia, sentindo-se cansado(a), sem ter energia? - N011
# "Peso - Final (em kg) (3 inteiros e 1 casa decimal)" - P00104
# "Altura - Final (em cm) (3 inteiros)" - P00404
#'Em geral, o(a) Sr(a) costuma comer esse tipo de verdura ou legume - P01001'
# Em geral, quantas vezes por dia o(a) Sr(a) come frutas? - P019
# Em quantos dias da semana o(a) Sr(a) costuma tomar refrigerante? - P02002
# Que tipo de refrigerante o(a) Sr(a) costuma tomar? - P02102
# Nos últimos três meses, o(a) Sr(a) praticou algum tipo de exercício físico ou esporte? - P034
# Quantos dias por semana o(a) Sr(a) costuma  (costumava)praticar exercício físico ou esporte? - P035
# No seu trabalho, o(a) Sr(a) anda bastante a pé?  - P038
# No seu trabalho, o(a) Sr(a) faz faxina pesada, carrega peso ou faz outra atividade pesada que requer esforço físico intenso? - P039
# Em um dia normal, quanto tempo o(a) Sr(a) passa andando bastante a pé ou realizando essas atividades pesadas ou que requerem esforço físico no seu trabalho?Horas - P03905
# Para ir ou voltar do trabalho, o(a) Sr(a) faz algum trajeto a pé ou de bicicleta? - P040
# Atualmente, o(a) Sr(a) fuma algum produto do tabaco? -- P50
# E no passado, o(a) Sr(a) fumou algum produto do tabaco diariamente? -- P051
# Em média, quanto fuma por dia ou por semana Cigarros industrializados -- P05401
# Quantos  por dia?  P05402
# Algum médico já lhe deu o diagnóstico de hipertensão arterial (pressão alta)? -- Q00201
# Algum médico já lhe deu o diagnóstico de diabetes? -- Q03001
# Algum médico já lhe deu o diagnóstico de colesterol alto? -- Q060
# Algum médico já lhe deu o diagnóstico de uma doença do coração, tal como infarto, angina, insuficiência cardíaca ou outra? -- Q06306
# Algum médico já lhe deu o diagnóstico de AVC (Acidente Vascular Cerebral) ou derrame? -- Q068
# Algum médico já lhe deu o diagnóstico de insuficiência renal crônica? -- Q124






































