# -*- coding: utf-8 -*-
"""Tratando_dados_dicionario.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1lAayNoVnzCttKIKCT3KH2v95QQEXn4Cl
"""

# Carregando os pacotes
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', None)

# dicionário dos dados
df = pd.read_excel('/content/dicionario_PNS_microdados_2019.xls', skiprows=1)

df.head()

# Pegando as colunas de interesse
colunas = ['Código\nda\nvariável','Unnamed: 4','Categorias','Unnamed: 6']

df = df[colunas]

# Remova as linhas com NA na coluna "tipo"
df = df.dropna(subset=['Categorias'])

# Removendo a primeira linha
df = df.drop(df.index[0])

# Renomeando as colunas
df = df.rename(columns={
    'Código\nda\nvariável': 'Codigo da variavel',
    'Unnamed: 4': 'Descricao_variavel',
    'Categorias': 'Tipo',
    'Unnamed: 6': 'Descricao_tipo'
})

df['Codigo da variavel'] = df['Codigo da variavel'].fillna(method='ffill')
df['Descricao_variavel'] = df['Descricao_variavel'].fillna(method='ffill')

df.head(5)